apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: true
    basicAuthUser: container_monitoring
    secureJsonData:
      basicAuthPassword: container_monitoring
    isDefault: true
    editable: true
