apiVersion: 1

datasources:
  - name: ClickHouse
    uid: ClickHouse
    version: 2
    type: grafana-clickhouse-datasource
    access: proxy
    basicAuth: true
    basicAuthUser: container_monitoring
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: container_monitoring
      defaultDatabase: default
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: container_monitoring
      password: container_monitoring
    isDefault: true
    editable: true
