// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/alert-rules": {
            "get": {
                "description": "Returns enabled and disabled threshold alert rules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert-rules"
                ],
                "summary": "List alert rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.AlertRule"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a threshold alert rule. Missing id, operator, duration, severity, recovery_policy, and enabled fields are defaulted by the API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert-rules"
                ],
                "summary": "Create alert rule",
                "parameters": [
                    {
                        "description": "Alert rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AlertRule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.AlertRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/alert-rules/{id}": {
            "delete": {
                "description": "Deletes a threshold alert rule.",
                "tags": [
                    "alert-rules"
                ],
                "summary": "Delete alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alert rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates a threshold alert rule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alert-rules"
                ],
                "summary": "Update alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alert rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Alert rule",
                        "name": "rule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AlertRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AlertRule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/events": {
            "get": {
                "description": "Returns recent container events from PostgreSQL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "List events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum rows",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Event"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incidents": {
            "get": {
                "description": "Returns recent incidents ordered by start time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incidents"
                ],
                "summary": "List incidents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Incident"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incidents/{id}": {
            "get": {
                "description": "Returns one incident by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "incidents"
                ],
                "summary": "Get incident",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incident ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Incident"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incidents/{id}/ack": {
            "post": {
                "description": "Marks an incident as acknowledged.",
                "tags": [
                    "incidents"
                ],
                "summary": "Acknowledge incident",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incident ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/incidents/{id}/resolve": {
            "post": {
                "description": "Marks an incident as resolved and sets resolved_at.",
                "tags": [
                    "incidents"
                ],
                "summary": "Resolve incident",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Incident ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/history": {
            "get": {
                "description": "Returns metric history points from ClickHouse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Metric history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "target_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "metric_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 start time",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 end time",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum rows",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.MetricPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/metrics/latest": {
            "get": {
                "description": "Returns recent metric snapshots from ClickHouse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Latest metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "target_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum rows",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.MetricSnapshot"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recovery-actions": {
            "get": {
                "description": "Returns recent recovery action attempts and results.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "List recovery actions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.RecoveryAction"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recovery-actions/{id}/retry": {
            "post": {
                "description": "Accepts a retry request for a recovery action placeholder endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Retry recovery action",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Recovery action ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.retryRecoveryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/targets": {
            "get": {
                "description": "Returns discovered Docker container targets.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "List targets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Target"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates or registers a monitored container target.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Create target",
                "parameters": [
                    {
                        "description": "Target",
                        "name": "target",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Target"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Target"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/targets/{id}": {
            "get": {
                "description": "Returns one discovered Docker container target.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Get target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Target"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a target record from the configuration store.",
                "tags": [
                    "targets"
                ],
                "summary": "Delete target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates target metadata used by the admin panel.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "targets"
                ],
                "summary": "Update target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Target",
                        "name": "target",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Target"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Target"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/targets/{id}/events": {
            "get": {
                "description": "Documents target-scoped event access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Target events pointer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum rows",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Event"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/targets/{id}/metrics": {
            "get": {
                "description": "Documents target-scoped metric history access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Target metrics pointer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Metric name",
                        "name": "metric_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum rows",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.MetricPoint"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Reports that the HTTP process is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Reports that the HTTP process is ready to serve requests.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.statusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AlertRule": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string",
                    "example": "2m"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "metric_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "recovery_policy": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "threshold": {
                    "type": "number"
                }
            }
        },
        "domain.Event": {
            "type": "object",
            "properties": {
                "container_name": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "severity": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.Incident": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "string"
                },
                "rule_id": {
                    "type": "string"
                },
                "severity": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "domain.MetricPoint": {
            "type": "object",
            "properties": {
                "container_name": {
                    "type": "string"
                },
                "metric_name": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "domain.MetricSnapshot": {
            "type": "object",
            "properties": {
                "block_read_bytes": {
                    "type": "integer"
                },
                "block_write_bytes": {
                    "type": "integer"
                },
                "container_name": {
                    "type": "string"
                },
                "cpu_usage_percent": {
                    "type": "number"
                },
                "memory_usage_bytes": {
                    "type": "integer"
                },
                "network_rx_bytes": {
                    "type": "integer"
                },
                "network_tx_bytes": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.RecoveryAction": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "incident_id": {
                    "type": "integer"
                },
                "result_message": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                }
            }
        },
        "domain.Target": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "external_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "last_seen_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "http.retryRecoveryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "status": {
                    "type": "string",
                    "example": "retry accepted"
                }
            }
        },
        "http.statusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Container Monitoring API",
	Description:      "MVP API for Docker container monitoring, alerting, incidents, and recovery actions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
